export const productItems = [
  { category: 'Cereals', imageUrl: 'https://placehold.co/250x250', name: 'Rice', price: 15.99 },
  { category: 'Cereals', imageUrl: 'https://placehold.co/250x250', name: 'Wheat', price: 12.49 },
  { category: 'Cereals', imageUrl: 'https://placehold.co/250x250', name: 'Oats', price: 10.99 },
  { category: 'Cereals', imageUrl: 'https://placehold.co/250x250', name: 'Barley', price: 11.49 },
  { category: 'Cereals', imageUrl: 'https://placehold.co/250x250', name: 'Millet', price: 14.79 },
  { category: 'Cereals', imageUrl: 'https://placehold.co/250x250', name: 'Rye', price: 13.39 },
  { category: 'Cereals', imageUrl: 'https://placehold.co/250x250', name: 'Sorghum', price: 16.19 },
  { category: 'Cereals', imageUrl: 'https://placehold.co/250x250', name: 'Corn', price: 12.99 },
  { category: 'Cereals', imageUrl: 'https://placehold.co/250x250', name: 'Cracked wheat', price: 14.29 },
  { category: 'Cereals', imageUrl: 'https://placehold.co/250x250', name: 'Refined Flour', price: 11.99 },
  { category: 'Cereals', imageUrl: 'https://placehold.co/250x250', name: 'Semolina', price: 13.89 },
  { category: 'Pulses', imageUrl: 'https://placehold.co/250x250', name: 'Pigeon Peas', price: 14.59 },
  { category: 'Pulses', imageUrl: 'https://placehold.co/250x250', name: 'Green Gram', price: 15.29 },
  { category: 'Pulses', imageUrl: 'https://placehold.co/250x250', name: 'Split Green Gram', price: 13.49 },
  { category: 'Pulses', imageUrl: 'https://placehold.co/250x250', name: 'Yellow Lentil', price: 16.99 },
  { category: 'Pulses', imageUrl: 'https://placehold.co/250x250', name: 'Split Red Lintel', price: 12.79 },
  { category: 'Pulses', imageUrl: 'https://placehold.co/250x250', name: 'Bengal Gram', price: 14.19 },
  { category: 'Pulses', imageUrl: 'https://placehold.co/250x250', name: 'Red kidney beans', price: 15.89 },
  { category: 'Pulses', imageUrl: 'https://placehold.co/250x250', name: 'Adzuki Beans', price: 13.99 },
  { category: 'Pulses', imageUrl: 'https://placehold.co/250x250', name: 'Dried Green Peas', price: 12.39 },
  { category: 'Pulses', imageUrl: 'https://placehold.co/250x250', name: 'Garbanzo Beans', price: 11.79 },
  { category: 'Pulses', imageUrl: 'https://placehold.co/250x250', name: 'Bengal gram Split And Skinned', price: 13.99 },
  { category: 'Pulses', imageUrl: 'https://placehold.co/250x250', name: 'Field Bean', price: 14.49 },
  { category: 'Pulses', imageUrl: 'https://placehold.co/250x250', name: 'Peas', price: 15.59 },
  { category: 'Spices', imageUrl: 'https://placehold.co/250x250', name: 'Cumin Seeds', price: 11.19 },
  { category: 'Spices', imageUrl: 'https://placehold.co/250x250', name: 'Coriander Leaves', price: 12.99 },
  { category: 'Spices', imageUrl: 'https://placehold.co/250x250', name: 'Coriander Seeds', price: 14.49 },
  { category: 'Spices', imageUrl: 'https://placehold.co/250x250', name: 'Turmeric', price: 13.59 },
  { category: 'Spices', imageUrl: 'https://placehold.co/250x250', name: 'Chilli Powder', price: 14.29 },
  { category: 'Spices', imageUrl: 'https://placehold.co/250x250', name: 'Salt', price: 10.49 },
  { category: 'Spices', imageUrl: 'https://placehold.co/250x250', name: 'Rock Salt', price: 11.79 },
  { category: 'Spices', imageUrl: 'https://placehold.co/250x250', name: 'Red Chilli', price: 13.99 },
  { category: 'Spices', imageUrl: 'https://placehold.co/250x250', name: 'Green Cardamom', price: 15.79 },
  { category: 'Spices', imageUrl: 'https://placehold.co/250x250', name: 'Garlic', price: 12.39 },
  { category: 'Spices', imageUrl: 'https://placehold.co/250x250', name: 'Fenugreek Seeds', price: 13.99 },
  { category: 'Spices', imageUrl: 'https://placehold.co/250x250', name: 'Dry Fenugreek Leaves', price: 15.49 },
  { category: 'Spices', imageUrl: 'https://placehold.co/250x250', name: 'Coriander Powder', price: 14.99 },
  { category: 'Spices', imageUrl: 'https://placehold.co/250x250', name: 'Cloves', price: 16.49 },
  { category: 'Spices', imageUrl: 'https://placehold.co/250x250', name: 'Caraway Seeds', price: 13.79 },
  { category: 'Spices', imageUrl: 'https://placehold.co/250x250', name: 'Black Mustard Seeds', price: 12.49 },
  { category: 'Spices', imageUrl: 'https://placehold.co/250x250', name: 'Indian Bay Leaf', price: 11.99 },
  { category: 'Spices', imageUrl: 'https://placehold.co/250x250', name: 'Asafoetida', price: 15.29 }
];
